$env:PROJECTREGION="us-east-1"
$env:CONGNITOIDENTITYPOOLID=""
$env:COGNITOUSERPOOLID="us-east-1_FLDoOLi1b"
$env:COGNITOAPPCLIENTID="2cbcsqn97k4t5i3r3mhtlf8tj3"
$env:S3BUCKETURL=""
$env:APISERVICEURL="https://i04st6u0dh.execute-api.us-east-1.amazonaws.com"
$env:TENANTID="A"
$env:PROJECTREGION
$env:TENANTID