#!/bin/bash -x

export PROJECTREGION="us-east-1"
export CONGNITOIDENTITYPOOLID=""
export COGNITOUSERPOOLID="us-east-1_FLDoOLi1b"
export COGNITOAPPCLIENTID="2cbcsqn97k4t5i3r3mhtlf8tj3"
export S3BUCKETURL=""
export APISERVICEURL="https://i04st6u0dh.execute-api.us-east-1.amazonaws.com"
export TENANTID="A"

echo "PROJECTREGION" $PROJECTREGION
echo "CONGNITOIDENTITYPOOLID" $CONGNITOIDENTITYPOOLID
echo "COGNITOUSERPOOLID" $COGNITOUSERPOOLID
echo "COGNITOAPPCLIENTID" $COGNITOAPPCLIENTID
echo "S3BUCKETURL" $S3BUCKETURL
echo "APISERVICEURL" $APISERVICEURL
echo "TENANTID" $TENANTID
